### ISSUE TITLE
Ensure that jobs emit usage help

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/dataflow-java#27]
It would be nice if when jobs are run with no arguments or `--help` that they print out usage details.

```
java -cp target/google-genomics-dataflow-v1beta2-0.2-SNAPSHOT.jar com.google.cloud.genomics.dataflow.pipelines.IdentityByState 
Exception in thread "main" java.lang.IllegalArgumentException: Need to specify either --genomicsSecretsFile or --apiKey
        at com.google.cloud.genomics.dataflow.utils.GenomicsOptions$Methods.validateOptions(GenomicsOptions.java:42)
        at com.google.cloud.genomics.dataflow.utils.GenomicsDatasetOptions$Methods.validateOptions(GenomicsDatasetOptions.java:63)
        at com.google.cloud.genomics.dataflow.pipelines.IdentityByState.main(IdentityByState.java:55)
```

**Comment by pgrosu** [comment]
Hi Nicole,
 
 It's easier than you think via an executable jar.  So the first thing is to create a main class, let's say in `src/main/java/com/google/cloud/genomics/dataflow/` and for now we can call it `DataFlowCLI.java`.   Below is a sample code, where basically all your help information will go:
 
 ```java
import java.io.IOException;

public class DataFlowCLI{
public static void main(String[] args) throws IOException {

    System.out.println("\n  To use dataflow below are some examples:\n\n" );

    System.out.println("  java -jar target/google-genomics-dataflow-v1beta2-0.2-SNAPSHOT.jar \n    com.google.cloud.genomics.dataflow.pipelines.VariantSimilarity \\ \n    --project=my-project-id \\ \n    --output=gs://my-bucket/output/localtest.txt \\ \n    --genomicsSecretsFile=client_secrets.json \n\n" );


  }
}
```

Then in the `pom.xml` file just add another plugin section that will make it an executable jar, and where you specify what the main file to run is:

```
 <plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-jar-plugin</artifactId>
   <version>2.4</version>
   <configuration>
     <archive>
       <manifest>
         <addClasspath>true</addClasspath>
         <classpathPrefix>lib/</classpathPrefix>
         <mainClass>com.google.cloud.genomics.dataflow.DataFlowCLI</mainClass>
        </manifest>
      </archive>
    </configuration>
  </plugin>

```

Then after you `mvn compile ; mvn bundle:bundle`, you can run it like this.  Below is the result:

```
$ java -jar target/google-genomics-dataflow-v1beta2-0.2-SNAPSHOT.jar

  To use dataflow below are some examples:


  java -jar target/google-genomics-dataflow-v1beta2-0.2-SNAPSHOT.jar
    com.google.cloud.genomics.dataflow.pipelines.VariantSimilarity \
    --project=my-project-id \
    --output=gs://my-bucket/output/localtest.txt \
    --genomicsSecretsFile=client_secrets.json

$
```

Hope it helps,
~p

**Comment by deflaux** [comment]
Fixed via https://github.com/googlegenomics/dataflow-java/pull/47
