### ISSUE TITLE
java.lang.ClassNotFoundException: javassist.bytecode.ClassFile

### ISSUE THREAD

**Issue by reprogrammer** [googlegenomics/dataflow-java#9]
```
$ java -cp target/googlegenomics-dataflow-java-v1beta2.jar   com.google.cloud.genomics.dataflow.pipelines.VariantSimilarity   --project=google.com:genomics-api   --output=gs://cloud-genomics-dataflow-tests/output/localtest.txt
```

```
Nov 15, 2014 11:51:11 AM com.google.cloud.genomics.dataflow.pipelines.VariantSimilarity getShardedRequests
INFO: Adding request with 17 41196312 to 41277500
Nov 15, 2014 11:51:11 AM com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner fromOptions
INFO: Creating DirectPipelineRunner
Nov 15, 2014 11:51:11 AM com.google.cloud.dataflow.sdk.Pipeline create
INFO: Creating Pipeline#111217068
Nov 15, 2014 11:51:11 AM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coders for genomics classes
Exception in thread "main" java.lang.NoClassDefFoundError: javassist/bytecode/ClassFile
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	at org.reflections.Reflections.scan(Reflections.java:243)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds.registerGenomicsCoders(DataflowWorkarounds.java:127)
	at com.google.cloud.genomics.dataflow.pipelines.VariantSimilarity.main(VariantSimilarity.java:143)
Caused by: java.lang.ClassNotFoundException: javassist.bytecode.ClassFile
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 8 more
```

**Comment by deflaux** [comment]
This issue will be taken care of via https://github.com/googlegenomics/dataflow-java/issues/60 when we do away with the DataflowWorkarounds class in favor of [registry.setFallbackCoderProvider](https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/coders/CoderRegistry#setFallbackCoderProvider(com.google.cloud.dataflow.sdk.coders.CoderProvider)) and the [code and tests](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/search?utf8=%E2%9C%93&q=setFallbackCoderProvider).

**Comment by mygit-lx** [comment]
I hava the same issue.
